apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: {{ template "chart.fullname" . }}-elasticsearch
  labels:
    app: {{ template "chart.name" . }}-elasticsearch
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  serviceName: {{ template "chart.fullname" . }}-elasticsearch
  selector:
    matchLabels:
      app: {{ template "chart.name" . }}-elasticsearch
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "chart.name" . }}-elasticsearch
        release: {{ .Release.Name }}
    spec:
      initContainers:
        - name: set-permissions
          image: busybox:1.28.4
          command: ["sh", "-c", "mkdir -p /mnt/elasticsearch && chown 1000:1000 /mnt/elasticsearch"]
          volumeMounts:
            - name: data
              mountPath: /mnt
        - name: set-sysctl
          image: busybox:1.28.4
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
      containers:
        - name: elastic
          image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9200
            - containerPort: 9300
          env:
            - name: discovery.type
              value: single-node
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
              subPath: elasticsearch
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: {{ .Values.elasticsearch.volume.storageClassName }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "chart.fullname" . }}-elasticsearch
  labels:
    app: {{ template "chart.name" . }}-elasticsearch
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "chart.name" . }}-elasticsearch
    release: {{ .Release.Name }}
  ports:
    - port: 9200
      name: http
    - port: 9300
      name: transport
  clusterIP: None