apiVersion: v1
kind: Service
metadata:
  name: {{ template "chart.fullname" . }}
  labels:
    app: {{ template "chart.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.externalPort }}
      targetPort: {{ .Values.service.http.internalPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.smtp.externalPort }}
      targetPort: {{ .Values.service.smtp.internalPort }}
      protocol: TCP
      name: smtp
  selector:
    app: {{ template "chart.name" . }}
    release: {{ .Release.Name }}
