---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.11.3
  creationTimestamp: null
  name: smtpservers.kube-mail.helmich.me
spec:
  group: kube-mail.helmich.me
  names:
    kind: SMTPServer
    listKind: SMTPServerList
    plural: smtpservers
    shortNames:
    - smtpserver
    singular: smtpserver
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: SMTP server hostname
      jsonPath: .spec.server
      name: SMTP Server
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: SMTPServer is the Schema for the smtpserver API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              authType:
                enum:
                - PLAIN
                - LOGIN
                - CRAM-MD5
                - SCRAM-SHA-1
                type: string
              connect:
                enum:
                - plain
                - ssl
                - starttls
                type: string
              port:
                type: integer
              server:
                type: string
              tls:
                description: 'DEPRECATED: Use Connect, instead'
                type: boolean
            required:
            - server
            type: object
          status:
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
