apiVersion: v2
description: A Helm chart for KubeMail
name: kube-mail
version: 0.10.4
dependencies:
  - name: redis
    version: 17.9.2
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
